### ISSUE TITLE
App does not request microphone access.

### ISSUE THREAD

**Issue by npes-95** [fwcd/m1xxx#26]
Hi,

Firstly, thanks for the work you've done making an m1 build available, it's really nice to have it running natively!

Unfortunately, I haven't been able to get my DVS setup working, the program does not detect the timecode signal coming from the audio interface. I suspect it might be because m1xxx does not request microphone access when starting up.

I didn't observe this behaviour with the official (intel) build, any idea what the issue could be? My best guesses are that the builds based off master do not currently support this, or alternatively, that the fact that this is an unofficial build restricts the access given to the program (launching the app requires going into system preferences and clicking "Open anyway"). I'm not a macOS expert, so any help with this would be amazing!

**Comment by fwcd** [comment]
Good question, some quick testing showed that the upstream Intel snapshots of Mixxx seem to have the same issue, whereas Mixxx 2.3 (stable) asks for microphone permissions. Therefore, since I'd assume this is an upstream issue, I have filed

- https://github.com/mixxxdj/mixxx/issues/11365

**Comment by npes-95** [comment]
Nice, thanks for investigating :)

**Comment by fwcd** [comment]
https://github.com/mixxxdj/mixxx/pull/11367 was merged to the 2.3 branch, so it should be available in 2.4 and `main` soon.
